services:
  - type: web
    name: it-park-smart-search
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/companies
    autoDeploy: true
